# Generated by Django 5.2.2 on 2025-06-24 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0005_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2025, 6, 24, 21, 5, 34, 852035)),
        ),
    ]
